name: dart_assignment
description: Dart Programming Assignment with Auto-grading
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: ^1.24.0

dev_dependencies:
  lints: ^3.0.0
